sudo: required
services:
  - docker

before_install:
  - docker build -t kat201/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kat201/react-test npm test -- --coverage

after_success:
  - docker build -t kat201/multi-client ./client
  - docker build -t kat201/multi-nginx ./nginx
  - docker build -t kat201/multi-server ./server
  - docker build -t kat201/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kat201/multi-client
  - docker push kat201/multi-nginx
  - docker push kat201/multi-server
  - docker push kat201/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-001959195903
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secure_access_key:
      secure: $AWS_SECRET_KEY
